# Generated by Django 5.1.6 on 2025-03-25 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('calculated_hash', models.CharField(max_length=64)),
                ('reference_hash', models.CharField(max_length=64)),
                ('algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha256', 'SHA-256')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField()),
            ],
        ),
    ]
