# Generated by Django 5.1.6 on 2025-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
