# Generated by Django 5.1.6 on 2025-03-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanresult_engines_scanresult_file_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='engines',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='file_details',
        ),
    ]
