# Generated by Django 5.1.6 on 2025-03-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_remove_scanresult_engines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='engines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='file_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
