# Generated by Django 5.1.6 on 2025-03-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanresult_engines_scanresult_file_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scan_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
