# Generated by Django 5.1.6 on 2025-03-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_alter_scanresult_scan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='scan_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='engines',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='file_details',
        ),
    ]
