# Generated by Django 5.1.6 on 2025-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_scanresult_vt_analysis_id_alter_scanresult_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
