# Generated by Django 5.1.6 on 2025-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_scanresult_file_hash_alter_scanresult_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
