# Generated by Django 5.1.6 on 2025-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
    ]
